YOUR NAME
 - Collaborator 1
 - Collaborator 2
 - etc

DS325, Gettysburg College, Professor Eatai Roth
# Problem Set 2 - Classification

Due Friday Mar 28, 2025 4p

Total pts: 30

## IMPORTANT INSTRUCTIONS:

 - When you submit your code, make sure that every cell runs without returning an error.
 - Once you have the results you need, edit out any extraneous code and outputs.
 - *Do not rewrite code* if it doesn't need to be rewritten. For example, all the import statements you should need are in the first code block. Do not redo those in your analysis.

## Problem 1

In this problem, you'll be comparing Logistic Regression, Decision Trees, and Random Forests in a task identifying mushrooms as edible or poisonous.
The data is imported below and the features and feature values are listed. Notice, they're all letters.

 - Split the data into targets and features
 - Decide which features are ordinal or categorical. Refer to the feature descriptions on the [UCI Machine Learning site](https://archive.ics.uci.edu/dataset/73/mushroom) (hint: at least 3 categories are ordinal and others are binary...so you'll use an ordinal encoder)
 - Encode the features
 - Train the three models. You will want to use ```LogisticRegressionCV``` and ```GridSearchCV``` to find the best version of each model.
 - Make predictions with your models.
 - Show the confusion matrices for each type of model evaluated on the same test set. Label each figure clearly as to which model it is.

In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score


mushrooms_df = pd.read_csv('https://raw.githubusercontent.com/stedy/Machine-Learning-with-R-datasets/refs/heads/master/mushrooms.csv')

for k, col in enumerate(mushrooms_df.columns):
    print(f'{k:>3}. {col} - {mushrooms_df[col].unique()}')

  0. type - ['p' 'e']
  1. cap_shape - ['x' 'b' 's' 'f' 'k' 'c']
  2. cap_surface - ['s' 'y' 'f' 'g']
  3. cap_color - ['n' 'y' 'w' 'g' 'e' 'p' 'b' 'u' 'c' 'r']
  4. bruises - ['t' 'f']
  5. odor - ['p' 'a' 'l' 'n' 'f' 'c' 'y' 's' 'm']
  6. gill_attachment - ['f' 'a']
  7. gill_spacing - ['c' 'w']
  8. gill_size - ['n' 'b']
  9. gill_color - ['k' 'n' 'g' 'p' 'w' 'h' 'u' 'e' 'b' 'r' 'y' 'o']
 10. stalk_shape - ['e' 't']
 11. stalk_root - ['e' 'c' 'b' 'r' '?']
 12. stalk_surface_above_ring - ['s' 'f' 'k' 'y']
 13. stalk_surface_below_ring - ['s' 'f' 'y' 'k']
 14. stalk_color_above_ring - ['w' 'g' 'p' 'n' 'b' 'e' 'o' 'c' 'y']
 15. stalk_color_below_ring - ['w' 'p' 'g' 'b' 'n' 'e' 'y' 'o' 'c']
 16. veil_type - ['p']
 17. veil_color - ['w' 'n' 'o' 'y']
 18. ring_number - ['o' 't' 'n']
 19. ring_type - ['p' 'e' 'l' 'f' 'n']
 20. spore_print_color - ['k' 'n' 'u' 'h' 'w' 'r' 'o' 'y' 'b']
 21. population - ['s' 'n' 'a' 'v' 'y' 'c']
 22. habitat - ['u' 'g' 'm' 'd' 'p' 'w' 'l']


In [11]:
#Lable Encoding
label_encoders = {}
for col in mushrooms_df.columns:
    le = LabelEncoder()
    mushrooms_df[col] = le.fit_transform(mushrooms_df[col])
    label_encoders[col] = le

# Separate features (X) and target (y)
X = mushrooms_df.drop('type', axis=1)
y = mushrooms_df['type']  # 1 = poisonous, 0 = edible (after encoding, or vice versa)

print("X shape:", X.shape)
print("y shape:", y.shape)


X shape: (8124, 22)
y shape: (8124,)


In [15]:
#Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


In [16]:
# Logistic Regression parameters
param_grid_lr = {
    'C': [0.01, 0.1, 1, 10],
    'solver': ['lbfgs', 'liblinear']
}

# Decision Tree parameters
param_grid_dt = {
    'max_depth': [None, 5, 10, 15],
    'min_samples_split': [2, 5, 10]
}

# Random Forest parameters
param_grid_rf = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 5, 10],
    'min_samples_split': [2, 5]
}


In [22]:
#Train models using GridSearchCV
# Logistic Regression
lr = LogisticRegression(max_iter=200)
grid_lr = GridSearchCV(lr, param_grid_lr, cv=5, scoring='accuracy')
grid_lr.fit(X_train, y_train)

print("LogisticRegression")
print("Best Params:", grid_lr.best_params_)
print("Best CV Accuracy:", grid_lr.best_score_)

# Decision Tree
dt = DecisionTreeClassifier()
grid_dt = GridSearchCV(dt, param_grid_dt, cv=5, scoring='accuracy')
grid_dt.fit(X_train, y_train)

print("DecisionTree")
print("Best Params:", grid_dt.best_params_)
print("Best CV Accuracy:", grid_dt.best_score_)

# Random Forest
rf = RandomForestClassifier()
grid_rf = GridSearchCV(rf, param_grid_rf, cv=5, scoring='accuracy')
grid_rf.fit(X_train, y_train)

print("RandomForest")
print("Best Params:", grid_rf.best_params_)
print("Best CV Accuracy:", grid_rf.best_score_)

/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_ite

LogisticRegression
Best Params: {'C': 10, 'solver': 'liblinear'}
Best CV Accuracy: 0.9564547877065198
DecisionTree
Best Params: {'max_depth': None, 'min_samples_split': 2}
Best CV Accuracy: 1.0
RandomForest
Best Params: {'max_depth': None, 'min_samples_split': 2, 'n_estimators': 50}
Best CV Accuracy: 1.0


In [21]:
# Extract best estimators
best_lr = grid_lr.best_estimator_
best_dt = grid_dt.best_estimator_
best_rf = grid_rf.best_estimator_

models = {
    "Logistic Regression": best_lr,
    "Decision Tree": best_dt,
    "Random Forest": best_rf
}

for model_name, model in models.items():
    print(f"{model_name}")
    y_pred = model.predict(X_test)
    accuracy = model.score(X_test, y_test)
    print(f"Test Accuracy: {accuracy:.4f}")
    
    # Confusion Matrix & Classification Report
    cm = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix:")
    print(cm)
    print("Classification Report:")
    print(classification_report(y_test, y_pred))

Logistic Regression
Test Accuracy: 0.9551
Confusion Matrix:
[[799  44]
 [ 29 753]]
Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.95      0.96       843
           1       0.94      0.96      0.95       782

    accuracy                           0.96      1625
   macro avg       0.95      0.96      0.96      1625
weighted avg       0.96      0.96      0.96      1625

Decision Tree
Test Accuracy: 1.0000
Confusion Matrix:
[[843   0]
 [  0 782]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       843
           1       1.00      1.00      1.00       782

    accuracy                           1.00      1625
   macro avg       1.00      1.00      1.00      1625
weighted avg       1.00      1.00      1.00      1625

Random Forest
Test Accuracy: 1.0000
Confusion Matrix:
[[843   0]
 [  0 782]]
Classification Report:
              precision    recall  f1-sc

### Problem 1 questions

 - Which model was best?
 - What were the hyper-parameters of this model.
 - What were the accuracy, recall, and precision of the model.
 - Of accuracy, recall, precision, which did you use to decide the best model.

#### Your responses here:

- Which model: 
Decision Tree is the best, achieved 100% accuracy on the test set
- Hyper-parameters: 
'max_depth': None, 'min_samples_split': 2
- Metrics
    - Accuracy: 1.00
    - Recall: 1.00
    - Precision: 1.00
- How did you decide best? 
In this case, the Decision Tree scored 1.0 on every metric, so it clearly better than Logistic Regression (which had 0.95 accuracy)

## Problem 2

The NFL draft is coming up at the end of April. This is when NFL teams get to select college players to join their team. The draft comprises seven rounds over three days (day 1: round 1, day 2: rounds 2 and 3, day 3: rounds 4, 5, 6, 7) with teams taking turns selecting players. Better players tend to go in earlier rounds.

In this problem, you will try to predict whether defensive players are drafted on Day 1, 2, or 3 based on their performance in the NFL combine (an assay of physical skills).

The data are imported below.

 - Create a target variable for day 1, day 2, day 3 based on the round drafted.
 - Create the most accurate predictor you can using any method or subset of the data you choose. *You may not use round as a feature!*
 - Show the confusion matrix for your model and list the accuracy of your model.

In [25]:
nfl_draft = pd.read_csv('https://raw.githubusercontent.com/eatai/datasets/refs/heads/main/nfl_defensive_draft.csv')
display(nfl_draft.head())
print("Shape:", nfl_draft.shape)

Unnamed: 0  round  season                name   age position  \
0           0      1    2003   Dewayne Robertson  21.0       DL   
1           1      1    2003      Terence Newman  25.0       DB   
2           2      1    2003  Johnathan Sullivan  22.0       DL   
3           3      1    2003      Kevin Williams  23.0       DL   
4           4      1    2003       Terrell Suggs  20.0       LB   

       college_conference    height  weight  forty  vertical  broad_jump  \
0                     NaN  6.083333   317.0   5.15       NaN         NaN   
1   Big Twelve Conference  5.833333   189.0   4.37      41.0       136.0   
2                     NaN  6.250000   313.0   5.10       NaN         NaN   
3                     NaN  6.416667   304.0   4.81      30.0       112.0   
4  Pacific Ten Conference  6.250000   262.0   4.84       NaN         NaN   

   cone  shuttle  
0   NaN      NaN  
1  6.88     3.83  
2   NaN      NaN  
3  7.66     5.04  
4   NaN      NaN

Shape: (2303, 14)


In [35]:
#Create target column "draft_day"
def map_day(round_num):
    """
    Converts round number into 'day1', 'day2', or 'day3'.
    """
    if round_num == 1:
        return "day1"
    elif round_num in [2, 3]:
        return "day2"
    else:
        return "day3"

nfl_draft['draft_day'] = nfl_draft['round'].apply(map_day)
display(nfl_draft.head())

Unnamed: 0  round  season                name   age position  \
0           0      1    2003   Dewayne Robertson  21.0       DL   
1           1      1    2003      Terence Newman  25.0       DB   
2           2      1    2003  Johnathan Sullivan  22.0       DL   
3           3      1    2003      Kevin Williams  23.0       DL   
4           4      1    2003       Terrell Suggs  20.0       LB   

       college_conference    height  weight  forty  vertical  broad_jump  \
0                     NaN  6.083333   317.0   5.15       NaN         NaN   
1   Big Twelve Conference  5.833333   189.0   4.37      41.0       136.0   
2                     NaN  6.250000   313.0   5.10       NaN         NaN   
3                     NaN  6.416667   304.0   4.81      30.0       112.0   
4  Pacific Ten Conference  6.250000   262.0   4.84       NaN         NaN   

   cone  shuttle draft_day  
0   NaN      NaN      day1  
1  6.88     3.83      day1  
2   NaN      NaN      day1  
3  7.66     5.04      day1  
4   NaN      NaN      day1

In [27]:
#Train test split   
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [28]:
#Train Classifier 
clf = DecisionTreeClassifier(random_state=42)
clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [29]:
#Predict
y_pred = clf.predict(X_test)

In [36]:
# Confusion Matrix
cm = confusion_matrix(y_test, y_pred, labels=[1,2,3,4,5,6,7])
print("Confusion Matrix:")
print(cm)

# Accuracy
acc = accuracy_score(y_test, y_pred)
print(f"Accuracy: {acc:.4f}")

Confusion Matrix:
[[782   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0]]
Accuracy: 1.0000


### Problem 2 Questions

 - Which kind of model did you use and why did you choose it? I used a Decision Tree Classifier because it handles both numerical and categorical variables well and effective for multi-class classification.
 - What was your accuracy? 100%